# Enterprise Sales Intelligence & Decisiton Support System
Bu proje
- Satış verisi üretir
- Veriyi temizler
- Analiz eder
- Karar destek özeti üretir
- Excel raporu oluşturur

In [1]:
# data_generator.py -> generate_sales_data()
# analytics.py -> sales_matrix(), normalize_matrix(), performance_score(), city_sale(), product_sale(),monthly_trend()
# reporting.py -> decision_report()
#preprocessing.py -> preprocessing_data()

### 2- Veriyi üret

In [2]:
import numpy as np
import pandas as pd
from data_generator import generate_sales_data
from preprocessing import preprocessing_data
from analytics import city_sale, product_sale, monthly_trend
from reporting import decision_report

#Veriyi üret
new_df = generate_sales_data(size=1000) #ham verimiz
new_df.head(20) #ilk 20 tanesini verir

    CustomerID          Products      City     Month    Amount
0         2231               Hub    Samsun  February  10295.33
1         4164            Laptop    Mersin      July   9422.64
2         3113            Laptop       Van  February       NaN
3         4331      Fon Makinesi  İstanbul      June       NaN
4         1845  Camasir Makinesi    Mersin       May       NaN
5         2985             Phone      Rize     March       NaN
6         3302            Tablet      Rize      July       NaN
7         1715             Mouse   Denizli     March       NaN
8          398            Tablet    Ankara      June       NaN
9         4698             Mouse    Mersin     March       NaN
10        2799           Monitor       Van       May       NaN
11        1567          Keyboard    Ankara       May       NaN
12        1019             Mouse    Mersin      June   5900.63
13        2375             Phone     Aydın  February   6067.92
14        3570             Mouse   Denizli     April   6148.60
15        2797             Phone    Ankara  February   5183.10
16        1843           Monitor    Samsun       May  10790.44
17        1475  Camasir Makinesi    Ankara      June   3865.78
18        2456            Tablet    Mersin      June   4958.42
19        1180          Keyboard  İstanbul     April   5361.86

### 3- Veriyi temizle

In [6]:
clean_df = preprocessing_data(new_df) #preprocessing fonksiyonumuzda temizleme yapmıştık
clean_df.head(20)

Eksik veri sayısı: CustomerID       0
Products         0
City             0
Month            0
Amount           0
KDV              0
Sale Category    0
dtype: int64

,CustomerID,Products,City,Month,Amount,KDV,Sale Category
0,2231,HUB,Samsun,Feb,10295.33,12869.1625,Platinum
1,4164,LAPTOP,Mersin,Jul,9422.64,11778.3000,Platinum
2,3113,LAPTOP,Van,Feb,6569.91,8212.3875,High
3,4331,FON MAKINESI,İstanbul,Jun,6569.91,8212.3875,High
4,1845,CAMASIR MAKINESI,Mersin,May,6569.91,8212.3875,High
5,2985,PHONE,Rize,Mar,6569.91,8212.3875,High
6,3302,TABLET,Rize,Jul,6569.91,8212.3875,High
7,1715,MOUSE,Denizli,Mar,6569.91,8212.3875,High
8,398,TABLET,Ankara,Jun,6569.91,8212.3875,High
9,4698,MOUSE,Mersin,Mar,6569.91,8212.3875,High
10,2799,MONITOR,Van,May,6569.91,8212.3875,High
11,1567,KEYBOARD,Ankara,May,6569.91,8212.3875,High
12,1019,MOUSE,Mersin,Jun,5900.63,7375.7875,High
13,2375,PHONE,Aydın,Feb,6067.92,7584.9000,High
14,3570,MOUSE,Denizli,Apr,6148.60,7685.7500,High
15,2797,PHONE,Ankara,Feb,5183.10,6478.8750,High
16,1843,MONITOR,Samsun,May,10790.44,13488.0500,Platinum
17,1475,CAMASIR MAKINESI,Ankara,Jun,3865.78,4832.2250,Standard
18,2456,TABLET,Mersin,Jun,4958.42,6198.0250,High
19,1180,KEYBOARD,İstanbul,Apr,5361.86,6702.3250,High

### 4- Analiz et

In [4]:
#analytics.py dosyamızdan alacağız
city_analysis = city_sale(clean_df) #şehir bazlı sum/mean/count
product_analysis = product_sale(clean_df) #ürün bazlı
monthly_analysis = monthly_trend(clean_df) #ay bazlı

### 5-Sonuçları Yazdır

In [7]:
#raporu alalım (sehir ve ürün)
rapor = decision_report(city_report = city_analysis, product_report=product_analysis) #best/worst city, best product, has risk getirir

#şehirleri bölgeye yazalım:
city_to_region= {
    "İstanbul" : "Marmara",
    "Ankara" : "Ic Anadolu",
    "Mersin" : "Akdeniz",
    "Rize" : "Karadeniz",
    "Van" : "Dogu Anadolu",
    "Aydın" : "Ege",
    "Konya": "Ic Anadolu" , 
    "Samsun": "Karadeniz",
    "Denizli" : "Ege"
}

#En iyi ay
best_month = monthly_analysis["sum"].idxmax()

#Riskli bölge (en kötü şehirden)
worst_c = rapor["Worst City"][0] #şehir, değer
risk_region = city_to_region.get(worst_c, "Unknown")

#Toplam satış
total_sale = clean_df["Amount"].sum()

En iyi şehir: ('İstanbul', 833713.38)
En kötü şehir: ('Denizli', 591318.82)
En karlı ürün: ('FON MAKINESI', 866850.9)
Riskli şehir yok.

### 6- Excel çıktısını al

In [9]:
file = "final_sales_report.xlsx"

with pd.ExcelWriter(file) as writer:
    #temiz veri
    clean_df.to_excel(writer, sheet_name = "Clean_Data", index=False)

    #analiz tabloları
    city_analysis.to_excel(writer, sheet_name="City_Analysis")
    product_analysis.to_excel(writer, sheet_name="Products_Analysis")
    monthly_analysis.to_excel(writer, sheet_name="Monthly_Analysis")

#Son çıktı
print(f"Toplam satış: {total_sale} TL.")
print(f"En karlı şehir: {rapor['Best City'][0]}")
print(f"En iyi ay: {best_month}")
print(f"Riskli bölge: {risk_region} Bölgesi")
print(f"Excel raporu oluşturuldu")

Toplam satış: 6747377.38 TL.
En karlı şehir: İstanbul
En iyi ay: Mar
Riskli bölge: Ege Bölgesi
Excel raporu oluşturuldu